---

- name: "{{ f5_license_state }} license on F5 big-ip"
  f5networks.f5_modules.bigip_device_license: 
    provider: "{{ f5_provider }}"
    accept_eula: "yes"
    state: "{{ f5_license_state }}"
    license_key: "{{ f5_license }}"
  notify: save config
  tags: [always]
