---

- include_tasks: facts.yml
  tags: 
    - facts
    - never

- name: L2 interface config 
  ios_l2_interfaces:
    config:
      - name: "{{ item.name }}"
        access: 
          vlan: "{{ item.access.vlan }}"
    state: merged
  loop: "{{ interface_config }}"
  notify: save config
  tags: [always, config]

- name: rollback interface config
  ios_config:
    lines: "default interface {{ item.name }}"
  loop: "{{ interface_config }}"
  tags: [never, rollback]
