---
# tasks file for virl

- include_tasks:
    file: virl_server.yml
  tags:
    - always

- include_tasks: 
    file: paloalto.yml
  when: virl_feature_palo

- include_tasks:
    file: prework.yml
  tags: always