---
# deploy VIRL server 

- name: SSH public key for VIRL
  packet_sshkey:
    auth_token: "{{ packet_token }}"
    key_file: "{{ packet_ssh_key_pub }}"
    label: "{{ packet_ssh_key_label }}"
  connection: local

- name: deploy / destroy Cisco VIRL server
  my_packet_device: 
    facility: "{{ packet_facility }}"
    project_id: "{{ packet_project }}"
    auth_token: "{{ packet_token }}"
    hostnames: "{{ packet_virl_hostname }}"
    operating_system: "{{ packet_virl_os }}"
    ipxe_script_url: "{{ packet_virl_url }}"
    wait_for_public_IPv: 4
    plan: "{{ packet_virl_plan }}"
    user_data: "{{ packet_virl_user_data }}"
    state: "{{ packet_virl_state }}"
  register: virl_server
  connection: local
  tags: 
    - destroy

- name: debug
  debug:
    msg: "{{ virl_server }}"
  tags: [ debug, never ]

- name: set VIRL facts
  set_fact:
    ansible_host: "{{ virl_server.devices[0].public_ipv4 }}"

- name: "waiting for ssh @{{ ansible_host }}"
  wait_for:
    delay: 1
    host: "{{ ansible_host }}"
    port: 22
    state: started
    timeout: 600
  connection: local

- name: ensure python interpreter
  set_fact: 
    ansible_python_interpreter: /usr/bin/python3

- name: fix virl.ini salt master server to EU
  replace:
    path: /etc/virl.ini
    replace: 'salt_master: vsm-eu-51.virl.info, vsm-eu-52.virl.info, vsm-eu-53.virl.info, vsm-eu-54.virl.info'
    regexp: '^salt_master:.*'
  become: true
  notify: reboot

- name: fix salt/minion.d master server 
  replace:
    path: /etc/salt/minion.d/extra.conf
    regexp: '^master: .*'
    replace: 'master: [vsm-eu-51.virl.info, vsm-eu-52.virl.info, vsm-eu-53.virl.info, vsm-eu-54.virl.info]'
  become: true
  notify: reboot
